
# Base data for all data sets --------------------------------------------------
library(S4Vectors)

df_Base <- DataFrame(
    BiocVersion = "3.13",
    SourceVersion = NA,
    Coordinate_1_based = TRUE,
    Species = "Homo sapiens",
    TaxonomyId = "9606",
    SourceVersion = Sys.time(),
    Genome = NA,
    SourceUrl = "https://doi.org/10.1038/s41467-020-18758-1",
    DataProvider = "https://figshare.com/articles/Multi_Omics_Seasonal_RData/12376508",
    Maintainer = "Sudarshan Shetty <sudarshanshetty9@gmail.com>"
)

df <- rbind(
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP gut microbiota counts",
                    Description = paste0("Gut microbiota count matrix for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "matrix",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/gutMicrobiota_relabundance.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP gut microbiota sample data",
                    Description = paste0("Gut microbiota sample data for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "DFrame",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/gutMicrobiota_coldata.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP nasal microbiota counts",
                    Description = paste0("Nasal microbiota count matrix for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "matrix",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/nasalMicrobiota_relabundance.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP nasal microbiota sample data",
                    Description = paste0("Nasal microbiota sample data for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "DFrame",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/nasalMicrobiota_coldata.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP RNAseq counts",
                    Description = paste0("RNAseq count matrix for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "matrix",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostTranscriptome_counts.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP RNAseq sample data",
                    Description = paste0("RNAseq sample data for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "DFrame",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostTranscriptome_coldata.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP proteome counts",
                    Description = paste0("Proteome count matrix for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "matrix",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostProteome_counts.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP proteome sample data",
                    Description = paste0("Proteome sample data for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "DFrame",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostProteome_coldata.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP metabolomics counts",
                    Description = paste0("Metabolomics count matrix for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "matrix",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostMetabolome_counts.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP metabolomics sample data",
                    Description = paste0("Metabolomics sample data for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "DFrame",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostMetabolome_coldata.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP cytokines counts",
                    Description = paste0("Cytokines count matrix for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "matrix",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostCytokines_counts.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP cytokines sample data",
                    Description = paste0("Cytokines sample data for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "DFrame",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostCytokines_coldata.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP clinical counts",
                    Description = paste0("Clinical count matrix for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "matrix",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostClinical_counts.rds",
                    Tags = NA)),
    cbind(df_Base,
          DataFrame(Title = "Sailani iPOP clinical sample data",
                    Description = paste0("Clinical sample data for the Sailani iPOP dataset"),
                    SourceType = "CSV",
                    RDataClass = "DFrame",
                    DispatchClass = "Rds",
                    RDataPath = "microbiomeDataSets/sailani-ipop/hostClinical_coldata.rds",
                    Tags = NA))
    
    
    
)

df$Tags <- paste(df$Tags[!is.na(df$Tags)],"Microbiome",collapse = ":",sep="")

write.csv(df, file = "inst/extdata/metadata-sailani-ipop.csv", row.names = FALSE)
